- name: "Generate server private key"
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: "wg genkey"
  register: server_private_key
  tags:
    - "keys"
    - "server"

- name: "Generate server public key"
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: "echo {{ server_private_key.stdout }} | wg pubkey"
  register: server_public_key
  tags:
    - "keys"
    - "server"

- name: "Write server private key to host"
  become: yes
  ansible.builtin.copy:
    content: "{{ server_private_key.stdout }}"
    dest: "/etc/wireguard/.privatekey"
    owner: root
    group: root
    mode: 0600
  tags:
    - "keys"
    - "server"

- name: "Write server public key to host"
  become: yes
  ansible.builtin.copy:
    content: "{{ server_public_key.stdout }}"
    dest: "/etc/wireguard/.publickey"
    owner: root
    group: root
    mode: 0600
  tags:
    - "keys"
    - "server"

- name: "Generate client private key"
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: "wg genkey"
  loop: "{{ wireguard.clients.peers }}"
  register: client_private_key
  tags:
    - "keys"
    - "clients"

- name: "Generate client public key"
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: "echo {{ client_private_key.results[index].stdout }} | wg pubkey"
  loop: "{{ wireguard.clients.peers }}"
  loop_control:
    index_var: index
  register: client_public_key
  tags:
    - "keys"
    - "clients"
