- name: "Create client configuration output path (if necessary)"
  delegate_to: "localhost"
  ansible.builtin.file:
    path: "{{ wireguard.clients.output_path }}"
    state: "directory"
  tags:
    - "configure"
    - "clients"

- name: "Generate client configuration files"
  delegate_to: "localhost"
  ansible.builtin.template:
    src: "../templates/client.conf.j2"
    dest: "{{ wireguard.clients.output_path }}/{{ item.name }}.conf"
  loop: "{{ wireguard.clients.peers }}"
  loop_control:
    index_var: index
  tags:
    - "configure"
    - "clients"
