- name: "(re)enable and (re)start wireguard service"
  become: "true"
  ansible.builtin.systemd:
    name: "wg-quick@wg0.service"
    enabled: "yes"
    daemon_reload: "yes"
    state: "restarted"
  tags:
    - "configure"
    - "install"
    - "server"
